[server]
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#D1495B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6F8"
textColor = "#18212B"
font = "sans serif"
